name: Update order status - Every 30 seconds cron job
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Every minute cron job
        run: |
          curl --request POST \
          --url 'http://localhost:3000/api/task' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
